In [1]:
import pandas as pd

In [2]:
# Load cleaned dataset
df = pd.read_csv("ola_cleaned.csv")

In [3]:
df

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,Reason for Cancelling by Customer,Cancelled Rides by Driver,Reason for Cancelling by Driver,Incomplete Rides,Incomplete Rides Reason,Booking Value,Payment Method,Ride Distance,Driver Ratings,Customer Rating
0,2024-01-28,1900-01-01 06:00:00,CNR1721175,Success,329258,Auto,Area-3,Area-2,5.42,18.46,...,NaN,0,NaN,0,NaN,868.06,Wallet,28.50,4.4,4.4
1,2024-01-26,1900-01-01 03:00:00,CNR2871422,Cancelled by Driver,201414,Mini,Area-7,Area-6,NaN,NaN,...,NaN,1,The customer was coughing/sick,0,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-01-15,1900-01-01 16:00:00,CNR6875935,Cancelled by Driver,301629,Bike,Area-40,Area-24,NaN,NaN,...,NaN,1,Personal & Car related issues,0,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-01-02,1900-01-01 22:00:00,CNR6798834,Cancelled by Driver,319684,Prime Sedan,Area-11,Area-24,NaN,NaN,...,NaN,1,The customer was coughing/sick,0,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-01-30,1900-01-01 22:00:00,CNR9661713,Incomplete,330283,Bike,Area-41,Area-45,NaN,NaN,...,NaN,0,NaN,1,Other Issue,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49994,2024-01-02,1900-01-01 00:00:00,CNR7299340,Success,454202,eBike,Area-39,Area-34,11.53,2.42,...,NaN,0,NaN,0,NaN,1217.43,Card,10.52,4.1,3.2
49995,2024-01-27,1900-01-01 02:00:00,CNR0378586,Success,349873,Auto,Area-17,Area-21,5.56,9.05,...,NaN,0,NaN,0,NaN,1369.51,UPI,11.04,5.0,4.3
49996,2024-01-17,1900-01-01 23:00:00,CNR2461856,Cancelled by Driver,880053,Auto,Area-37,Area-43,NaN,NaN,...,NaN,1,More than permitted people in there,0,NaN,NaN,NaN,NaN,NaN,NaN
49997,2024-01-18,1900-01-01 22:00:00,CNR9524579,Success,752806,eBike,Area-48,Area-29,5.15,13.72,...,NaN,0,NaN,0,NaN,1930.49,UPI,14.49,3.1,4.5
49998,2024-01-28,1900-01-01 14:00:00,CNR3698787,Success,159552,Bike,Area-1,Area-37,14.89,28.07,...,NaN,0,NaN,0,NaN,1534.66,Cash,4.60,3.3,4.1

In [4]:
# Convert Date and Time back to datetime
df["Date"] = pd.to_datetime(df["Date"])
df["Time"] = pd.to_datetime(df["Time"])

In [5]:
# Check dataset
df.head()

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,Reason for Cancelling by Customer,Cancelled Rides by Driver,Reason for Cancelling by Driver,Incomplete Rides,Incomplete Rides Reason,Booking Value,Payment Method,Ride Distance,Driver Ratings,Customer Rating
0,2024-01-28,1900-01-01 06:00:00,CNR1721175,Success,329258,Auto,Area-3,Area-2,5.42,18.46,...,NaN,0,NaN,0,NaN,868.06,Wallet,28.5,4.4,4.4
1,2024-01-26,1900-01-01 03:00:00,CNR2871422,Cancelled by Driver,201414,Mini,Area-7,Area-6,NaN,NaN,...,NaN,1,The customer was coughing/sick,0,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-01-15,1900-01-01 16:00:00,CNR6875935,Cancelled by Driver,301629,Bike,Area-40,Area-24,NaN,NaN,...,NaN,1,Personal & Car related issues,0,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-01-02,1900-01-01 22:00:00,CNR6798834,Cancelled by Driver,319684,Prime Sedan,Area-11,Area-24,NaN,NaN,...,NaN,1,The customer was coughing/sick,0,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-01-30,1900-01-01 22:00:00,CNR9661713,Incomplete,330283,Bike,Area-41,Area-45,NaN,NaN,...,NaN,0,NaN,1,Other Issue,NaN,NaN,NaN,NaN,NaN

In [6]:
# Year
df["Year"] = df["Date"].dt.year

In [7]:
# Quarter
df["Quarter"] = df["Date"].dt.quarter

In [8]:
# Month Number
df["Month"] = df["Date"].dt.month

In [9]:
# Month Name
df["Month Name"] = df["Date"].dt.month_name()

In [10]:
# Day of Month
df["Day"] = df["Date"].dt.day

In [11]:
# Day Name
df["Day Name"] = df["Date"].dt.day_name()

In [12]:
# Hour
df["Hour"] = df["Time"].dt.hour

In [13]:
def time_slot(hour):
    if 5 <= hour < 12:
        return "Morning"
    elif 12 <= hour < 17:
        return "Afternoon"
    elif 17 <= hour < 21:
        return "Evening"
    else:
        return "Night"

df["Time Slot"] = df["Hour"].apply(time_slot)

In [14]:
print(df[[
    "Year",
    "Quarter",
    "Month",
    "Month Name",
    "Day",
    "Day Name",
    "Hour",
    "Time Slot"
]].head())

   Year  Quarter  Month Month Name  Day Day Name  Hour  Time Slot
0  2024        1      1    January   28   Sunday     6    Morning
1  2024        1      1    January   26   Friday     3      Night
2  2024        1      1    January   15   Monday    16  Afternoon
3  2024        1      1    January    2  Tuesday    22      Night
4  2024        1      1    January   30  Tuesday    22      Night

In [15]:
print("Years:", df["Year"].unique())
print("Quarters:", df["Quarter"].unique())
print("Months:", df["Month Name"].unique())
print("Days:", df["Day Name"].unique())
print("Time Slots:", df["Time Slot"].unique())

Years: [2024]
Quarters: [1]
Months: ['January']
Days: ['Sunday' 'Friday' 'Monday' 'Tuesday' 'Wednesday' 'Thursday' 'Saturday']
Time Slots: ['Morning' 'Night' 'Afternoon' 'Evening']

In [16]:
df.to_csv("ola_feature_engineered.csv", index=False)

print("Feature Engineering Completed Successfully!")

Feature Engineering Completed Successfully!